cpu-type: X86O3CPU
num-cpus: 4
sys-clock: 1.5GHz
cpu-clock: 2.5GHz
mem-type: DDR4_2400_8x8
mem-size: 4GB
mem-channels: 2
mem-ranks: 2
caches: true
l2cache: true
l3cache: true
l1d_size: 64KiB
l1i_size: 64KiB
l2_size: 4MiB
l3_size: 32MiB
cacheline_size: 128
cmd: tests/test-progs/threads/bin/x86/linux/threads
options: 40000
